### ISSUE TITLE
panorama 项目中代码的几个疑问

### ISSUE THREAD

**Issue by kmfe** [songdy/songdy.github.io#1]
大佬你好，

你的panorama项目是我看到的全景里面最简洁的panorama类的项目 🤪
这段时间也正好在做类似这样的项目，其中借鉴了你的很多代码，有些代码有些疑问，想请教你下~

1. `buttonList` 初始化button参数，用的phi, theta 来标明位置，这个值不知道怎么来的，如何确定这两个值，目前做的项目使用经纬度来标示位置（缺点->不够精准），或者在后台也创建全景图，点击图片直接生成Vector3的位置信息来确定位置然后传递给前端(缺点 -> 麻烦)。

2. `createSpriteShape` 方法在创建热点的时候，scale 参数值分别设置成了12，24，36，实际项目中我使用图片创建热点，scale 设置到了30才勉强看到小按钮热点 (canvas 大小设置为80*80了)，我想请教下大佬，如何才能使用原始scale = 1 缩放比例也能正常显示热点大小。

😳菜狗坐等大佬回复~

**Comment by songdy** [comment]
1、phi, theta就是经纬度，的确是很难确定它们的值，可以考虑在全景图里面，捕获鼠标点击的坐标，转化phi, theta。
2、Sprite设置宽高就好了，应该是不受相机影响的。
（我是初学者，互勉）
